name: KineST
channels:
  - nvidia/label/cuda-11.8.0
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - pytorch
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.7.9
  - cuda-nvcc=11.8.89
  - cudatoolkit=11.8.0
  - intel-openmp=2023.1.0
  - joblib=1.4.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.17
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.10.16
  - readline=8.2
  - scikit-learn=1.6.1
  - scipy=1.15.3
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
    - accelerate==1.7.0
    - asttokens==3.0.0
    - body-visualizer==1.1.0
    - causal-conv1d==1.4.0
    - certifi==2025.4.26
    - charset-normalizer==3.4.2
    - colour==0.1.5
    - contourpy==1.3.2
    - cycler==0.12.1
    - decorator==5.2.1
    - diffusers==0.33.1
    - dotmap==1.3.30
    - easydict==1.13
    - einops==0.8.1
    - exceptiongroup==1.3.0
    - executing==2.2.0
    - filelock==3.13.1
    - fonttools==4.58.4
    - freetype-py==2.5.1
    - fvcore==0.1.5.post20221221
    - hf-xet==1.1.2
    - huggingface-hub==0.32.4
    - human-body-prior==2.1.2.0
    - idna==3.10
    - imageio==2.37.0
    - imageio-ffmpeg==0.6.0
    - importlib-metadata==8.7.0
    - iopath==0.1.10
    - ipdb==0.13.13
    - ipython==8.37.0
    - jedi==0.19.2
    - kiwisolver==1.4.8
    - lazy-loader==0.4
    - loguru==0.7.3
    - mamba-ssm==2.2.2
    - markupsafe==2.1.5
    - matplotlib==3.10.3
    - matplotlib-inline==0.1.7
    - moviepy==2.2.1
    - ninja==1.11.1.4
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cuda-cupti-cu11==11.8.87
    - nvidia-cuda-nvrtc-cu11==11.8.89
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cudnn-cu11==8.7.0.84
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.3.0.86
    - nvidia-cusolver-cu11==11.4.1.48
    - nvidia-cusparse-cu11==11.7.5.86
    - nvidia-ml-py==12.575.51
    - nvidia-nccl-cu11==2.20.5
    - nvidia-nvtx-cu11==11.8.86
    - nvitop==1.5.1
    - opencv-python==4.11.0.86
    - packaging==25.0
    - pandas==2.2.3
    - parso==0.8.4
    - pexpect==4.9.0
    - pillow==11.0.0
    - portalocker==3.2.0
    - prettytable==3.16.0
    - proglog==0.1.12
    - prompt-toolkit==3.0.51
    - protobuf==6.31.1
    - psutil==7.0.0
    - ptflops==0.7.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pyglet==1.5.27
    - pygments==2.19.1
    - pymotion==0.0.0
    - pyopengl==3.1.0
    - pyparsing==3.2.3
    - pyperclip==1.9.0
    - pyrender==0.1.43
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.1.1
    - pytz==2025.2
    - pyyaml==6.0.2
    - pyzmq==27.0.0
    - regex==2024.11.6
    - requests==2.32.3
    - safetensors==0.5.3
    - scikit-image==0.25.2
    - six==1.17.0
    - stack-data==0.6.3
    - sympy==1.14.0
    - tabulate==0.9.0
    - tensorboardx==2.6.2.2
    - termcolor==3.1.0
    - thop==0.1.1-2209072238
    - tifffile==2025.5.10
    - timm==1.0.15
    - tokenizers==0.19.1
    - tomli==2.2.1
    - torch==2.3.1+cu118
    - torchaudio==2.3.1+cu118
    - torchstat==0.0.7
    - torchvision==0.18.1+cu118
    - tqdm==4.67.1
    - traitlets==5.14.3
    - transformers==4.43.3
    - transforms3d==0.3.1
    - trimesh==3.9.5
    - triton==2.3.1
    - tzdata==2025.2
    - upc-pymotion==0.1.10
    - urllib3==2.4.0
    - wcwidth==0.2.13
    - yacs==0.1.8
    - zipp==3.22.0
    - zmq==0.0.0

